In [12]:
### Simple version with for loop for deep NNs
import numpy as np

def nn(inputs, weights, biases):
    """inputs is a 1 x m matrix of input values
       weights is a list of length n, each element is an m x p matrix
           of weights for a layer (incl. output layer)
       biases is a p x n matrix of biases (incl. output)
           so each column is the biases for one layer
    """
    # Calculate values for each layer
    for i in range(len(weights)):
        inputs = np.dot(inputs, weights[i]) + biases[:,i] # mat mult and bias
        inputs[inputs < 0] = 0
    return inputs

# Define the weights and biases
# This network will output a positive value if input1 >> input2,
# and vice versa.
# The biases determine the definition of ">>" and "<<"
hidden_weights = np.array([[1, -1],[-1, 1]])
output_weights = np.array([[1, 0],[0, 1]])
biases = np.array([[-1, 0], [-1, 0]])
weights = [hidden_weights, output_weights]

# Set example inputs
inputs = np.array([10,3])
nn(inputs, weights, biases)

array([6, 0])

In [13]:
# Can we make a nn for "o" responding to "x" move in tic tac toe?
# The inputs and outputs 1-9 are the cells ordered by row
# Strategy: If "x" goes in the center, go in a corner; if
# "x" goes anywhere else, go in the center.

inputs = np.array([0,0,0,0,0,1,0,0,0]).T # 3x3 board by rows
weights = [np.array([[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[0,0,0,0,1,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0]])]
biases = np.array([[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]]).T

nn(inputs, weights, biases)

array([1, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# This is the same version but with print statements
import numpy as np

def nn(inputs, weights, biases):
    """inputs is a 1 x m matrix of input values
       weights is a list of length n, each element is an m x p matrix
           of weights for a layer (incl. output layer)
       biases is a p x n matrix of biases (incl. output)
           so each column is the biases for one layer

       currently only works for 1 hidden layer
    """
    # Calculate values for each layer
    for i in range(len(weights)):
        print("")
        print(f'Layer {i}.')
        print('Inputs: ')
        print(inputs)
        
        inputs = np.dot(inputs, weights[i]) + biases[:,i] # mat mult and bias
        print('Inputs * weights + bias:')
        print(inputs)
        
        inputs[inputs < 0] = 0
        print('After ReLU activation:')
        print(inputs)

    return inputs
    
inputs = np.array([10,3])
hidden_weights = np.array([[1, -1],[-1, 1]])
output_weights = np.array([[1, 0],[0, 1]])
biases = np.array([[-1, 0], [-1, 0]])
weights = [hidden_weights, output_weights]
nn(inputs, weights, biases)



Layer 0.
Inputs: 
[10  3]
Inputs * weights + bias:
[ 6 -8]
After ReLU activation:
[6 0]

Layer 1.
Inputs: 
[6 0]
Inputs * weights + bias:
[6 0]
After ReLU activation:
[6 0]


array([6, 0])