In [16]:
### Neural network with 1 hidden layer
import numpy as np

def nn(inputs, weights, biases):
    """inputs is a 1 x m matrix of input values
       weights is a list of length n, each element is an m x p matrix
           of weights for a layer (incl. output layer)
       biases is a p x n matrix of biases (incl. output)
           so each column is the biases for one layer

       currently only works for 1 hidden layer
    """
    # Calculate values for hidden layer
    print("Input values:")
    print(inputs)
    print("Hidden layer weights:")
    print(weights[0])
    print("Multiplying inputs x weights:")
    hidden_values = np.dot(inputs, weights[0]) # matrix multiplication

    print(hidden_values)    
    print("Hidden layer biases:")
    print(biases[:,0])
    print("Adding biases:")
    hidden_values = hidden_values + biases[:,0] # add bias
    
    print(hidden_values)
    hidden_values[hidden_values < 0] = 0
    
    print("Final activation values after ReLU:")
    print(hidden_values)

    # Calculate values for output layer
    print("Output layer weights:")
    print(weights[1])
    print("Multiplying values x weights:")
    output_values = np.dot(hidden_values, weights[1]) # matrix multiplication

    print(output_values)
    print("Output layer biases:")
    print(biases[:,1])
    print("Adding biases:")
    output_values = output_values + biases[:,1]
    print(output_values) # for debugging purposes
    
inputs = np.array([10,3])
hidden_weights = np.array([[1, -1],[-1, 1]])
output_weights = np.array([[1, 0],[0, 1]])
biases = np.array([[-1, 0], [-1, 0]])
weights = [hidden_weights, output_weights]
nn(inputs, weights, biases)


Input values:
[10  3]
Hidden layer weights:
[[ 1 -1]
 [-1  1]]
Multiplying inputs x weights:
[ 7 -7]
Hidden layer biases:
[-1 -1]
Adding biases:
[ 6 -8]
Final activation values after ReLU:
[6 0]
Output layer weights:
[[1 0]
 [0 1]]
Multiplying values x weights:
[6 0]
Output layer biases:
[0 0]
Adding biases:
[6 0]


In [24]:
### Simpler version with for loop for deep NNs
import numpy as np

def nn(inputs, weights, biases):
    """inputs is a 1 x m matrix of input values
       weights is a list of length n, each element is an m x p matrix
           of weights for a layer (incl. output layer)
       biases is a p x n matrix of biases (incl. output)
           so each column is the biases for one layer
    """
    # Calculate values for each layer
    for i in range(len(weights)):
        inputs = np.dot(inputs, weights[i]) + biases[:,i] # mat mult and bias
        inputs[inputs < 0] = 0
        
    return inputs

inputs = np.array([10,3])
hidden_weights = np.array([[1, -1],[-1, 1]])
output_weights = np.array([[1, 0],[0, 1]])
biases = np.array([[-1, 0], [-1, 0]])
weights = [hidden_weights, output_weights]
nn(inputs, weights, biases)


array([6, 0])

In [47]:
###Can we make a nn for "o" responding to "x" move in tic tac toe?
inputs = np.array([0,0,0,0,0,1,0,0,0]).T # 3x3 board by rows
weights = [np.array([[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[0,0,0,0,1,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0],[1,0,0,0,0,0,0,0,0]])]
biases = np.array([[0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0]]).T
# np.dot(inputs, w
nn(inputs, weights, biases)

array([1, 0, 0, 0, 0, 0, 0, 0, 0])